### ISSUE TITLE
Update checksumthing

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/checksumthing#10]
Should we not add in the `README.md` how to update this tool? cc @henryborchers

**Comment by ablwr** [comment]
Like how to contribute? Also CONTRIBUTING.md placed in the top level of a Github directory allows the Contributing Guidelines to pop up upon PR-opening, etc. And can be linked in README.md.

**Comment by henryborchers** [comment]
@retokromer, what do you mean? 

Do you mean install updates? Since there are no "releases" for this tool, there are no real updates. It's just whatever the current version in HEAD of this repo. In that case to get the most current version, just clone the most reason repo and hope that it's not broken when you install it. 

I created a basic Jenkinsfile which could be used for automatically pushing out source builds to the Release tab in Github and updating the documentation as the program changes, but I'm not really interested in hosting a Jenkins server at home for this project. (My electrical bill is already too high) However, if someone has access to a server with Jenkins on it, feel free to use it.

We could add this to the various package managers (Homebrew, Aptitude, Chocolatey) to distribute it and manage updates through that. However, without a good test suite for the codebase, I feel very uncomfortable about doing that.

**Comment by retokromer** [comment]
I guess that for the λ-user it would be useful to indicate how to reinstall a newer «version» when we improve something.

Of course, Homebrew/Linuxbrew, Chocolatey, etc. would be ideal, but a first, useful step could be to publish the commands for reinstalling the current package. (Jenkins seems to me to be too much in this case.)

**Comment by henryborchers** [comment]
Well, there is a Jenkinsfile now for this project now. Using the new Groovy-style pipeline syntax, it builds, runs any unit tests in Python 2.7 and Python 3.5 and builds a new set of HTML documentation (and artifacts the docs as a tar.gz). If someone wanted to get serious about working on this, this should make that much easier for setting up a CI environment.

**Comment by retokromer** [comment]
Yes, thank you! Any volunteer out there?

**Comment by henryborchers** [comment]
While I have set this up for Jenkins, one could use travis-ci. I've never used it but it's supposed to be free for open source software projects and ties nicely into github. One would have to write a travis script for doing these same tasks.

**Comment by henryborchers** [comment]
@retokromer Also, I recently learned how to build Homebrew formulas for Python projects. For something this simple, it's actually pretty easy. Once the code here has enough unit tests, I'd be happy to write a Homebrew formula so that people can download it through that.

**Comment by ablwr** [comment]
+1 in favor of Travis-CI.

**Comment by retokromer** [comment]
Indeed, `travis-ci` is free for open source projects.

**Comment by retokromer** [comment]
:+1:  for a Homebrew/Linuxbrew formula

**Comment by kieranjol** [comment]
+1 homebrew

**Comment by retokromer** [comment]
This seems not be of interest.
